### ISSUE TITLE
Uncaught TypeError

### ISSUE THREAD

**Issue by optikfluffel** [adelinolobao/Space-Invaders-HTML-5#1]
I just tried to insert your game into a wordpress-blog and got this =(

```
Uncaught TypeError: Object function each(iterator, context) {
    var index = 0;
    try {
      this._each(function(value) {
        iterator.call(context, value, index++);
      });
    } catch (e) {
      if (e != $break) throw e;
    }
    return this;
  } has no method 'draw'
```

**Comment by adelinolobao** [comment]
Hum, I'm not seeing what is the problem... For the game work, you only need to have a canvas tag (with an id="content") and include all the script files.

**Comment by optikfluffel** [comment]
i've changed the id of this canvas but also changed it in the .js files etc.

**Comment by adelinolobao** [comment]
I'm not familiarized with the wordpress environment, and how do you embed things on it.
Looking to the error type, I think its an error on a for cycle, where all the elements of the game are draw. But I really don't know what is happening, because everything works fine when you try the game in a regular web page...
You need to give more details about the error.
